# Generated by Django 2.2.4 on 2019-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addr',
            field=models.CharField(default=32, max_length=32),
            preserve_default=False,
        ),
    ]
