# Generated by Django 2.2.4 on 2019-09-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_student_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='addr',
        ),
    ]
